---
title: "scratch_map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) 
library(datasets)
library(viridis)
library(maps)
library(leaflet)
library(shinythemes)
library(tidyverse)
library(rvest)
library(robotstxt)
library(tidycensus)
library(tidytext)
library(shiny)
```

```{r}
path_in <- "/Users/rodrigo/Git/Blog-Data-For-Good"
city_data <- read_csv(paste0(path_in, "/dataset.csv"))

#mean, standard deviation
mean <- mean(city_data$y2013_population[])
std_dev <- sd(city_data$y2013_population)

mean
#standar

mypal <- colorNumeric(
  palette = "Spectral",
  domain = city_data$y2013_population)

leaflet(data = city_data) %>% 
  addTiles() %>%
  setView(-72.5, 42.4, zoom = 3) %>%
  addCircleMarkers(lat=city_data$latitude
                   , lng=city_data$longitude
                   , fillColor = ~mypal(y2013_population)
                   , color = "#b2aeae"
                   , popup= paste0(city_data$name_simp,", ", city_data$state_abbrev,": ",city_data$y2013_population)
                   , stroke = FALSE
  
                   , radius = (city_data$y2013_population 
                               - mean(city_data$y2013_population))
                               / sd(city_data$y2013_population) * 3
                   , fillOpacity = 0.9)
```

